# ──────────────────────────────────────────────────────────────────────────────
# Mission Control — Multi-stage Docker build
#
# 1. Installs dependencies and optionally pushes Convex functions
# 2. Builds the Vite SPA with VITE_CONVEX_URL baked in
# 3. Serves the static bundle via `serve`
#
# Build args (for local/docker-compose builds):
#   VITE_CONVEX_URL                - URL the browser will use to reach Convex
#   CONVEX_SELF_HOSTED_URL         - URL the build container uses to push functions
#
# Secrets (for Convex push — pass via --secret):
#   convex_admin_key               - Admin key generated by the self-hosted backend
#
# For the pre-built image (ghcr.io/bidewio/mission-control):
#   Set VITE_CONVEX_URL at runtime via environment variable.
#   The entrypoint script injects it into the static JS bundle on startup.
# ──────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Build ───────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

# Build arguments
ARG VITE_CONVEX_URL=__MISSION_CONTROL_CONVEX_URL_PLACEHOLDER__
ARG CONVEX_SELF_HOSTED_URL

ENV VITE_CONVEX_URL=${VITE_CONVEX_URL}

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile || pnpm install

# Copy source (convex/_generated/ types are committed to the repo)
COPY . .

# Push Convex functions to self-hosted backend (schema + server functions)
# Uses --mount=type=secret to avoid leaking the admin key in image layers.
# Skipped when the secret or URL is not provided (e.g. CI image builds).
RUN --mount=type=secret,id=convex_admin_key \
    if [ -n "$CONVEX_SELF_HOSTED_URL" ] && [ -f /run/secrets/convex_admin_key ]; then \
    export CONVEX_SELF_HOSTED_ADMIN_KEY=$(cat /run/secrets/convex_admin_key) && \
    echo "Pushing Convex functions to self-hosted backend..." && \
    npx convex deploy --cmd 'echo "Functions pushed successfully"'; \
    else \
    echo "Skipping Convex push (CONVEX_SELF_HOSTED_URL or convex_admin_key secret not set)"; \
    fi

# Build the Vite SPA (VITE_CONVEX_URL is embedded at this step)
RUN pnpm run build

# ── Stage 2: Serve ───────────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 3660

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s --retries=3 \
    CMD wget -q --spider http://localhost:3660/ || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
