# ──────────────────────────────────────────────────────────────────────────────
# Mission Control — Multi-stage Docker build
#
# 1. Installs dependencies and pushes Convex functions to the self-hosted backend
# 2. Builds the Vite SPA with VITE_CONVEX_URL baked in
# 3. Serves the static bundle via `serve`
#
# Build args (for local/docker-compose builds):
#   VITE_CONVEX_URL                - URL the browser will use to reach Convex
#   CONVEX_SELF_HOSTED_URL         - URL the build container uses to push functions
#   CONVEX_SELF_HOSTED_ADMIN_KEY   - Admin key generated by the self-hosted backend
#
# For the pre-built image (ghcr.io/bidewio/mission-control):
#   Set VITE_CONVEX_URL at runtime via environment variable.
#   The entrypoint script injects it into the static JS bundle on startup.
# ──────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Build ───────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

# Build arguments (required for Convex push + Vite embed)
ARG VITE_CONVEX_URL=__MISSION_CONTROL_CONVEX_URL_PLACEHOLDER__
ARG CONVEX_SELF_HOSTED_URL
ARG CONVEX_SELF_HOSTED_ADMIN_KEY

# Make build args available as env vars during build
ENV VITE_CONVEX_URL=${VITE_CONVEX_URL}
ENV CONVEX_SELF_HOSTED_URL=${CONVEX_SELF_HOSTED_URL}
ENV CONVEX_SELF_HOSTED_ADMIN_KEY=${CONVEX_SELF_HOSTED_ADMIN_KEY}

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile || pnpm install

# Copy source
COPY . .

# Push Convex functions to self-hosted backend (schema + server functions)
# This step deploys your convex/ directory to the running Convex backend
RUN if [ -n "$CONVEX_SELF_HOSTED_URL" ] && [ -n "$CONVEX_SELF_HOSTED_ADMIN_KEY" ]; then \
    echo "Pushing Convex functions to self-hosted backend..." && \
    npx convex deploy --cmd 'echo "Functions pushed successfully"'; \
    else \
    echo "Skipping Convex push (CONVEX_SELF_HOSTED_URL or CONVEX_SELF_HOSTED_ADMIN_KEY not set)"; \
    fi

# Build the Vite SPA (VITE_CONVEX_URL is embedded at this step)
RUN pnpm run build

# ── Stage 2: Serve ───────────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 3660

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s --retries=3 \
    CMD wget -q --spider http://localhost:3660/ || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
